GOOSE_MODEL: gemini-2.5-pro
gemini-cli_configured: true
GOOSE_PROVIDER: gemini-cli
OLLAMA_HOST: localhost
GOOSE_ENABLE_ROUTER: 'true'
extensions:
  computercontroller:
    enabled: false
    type: builtin
    name: computercontroller
    display_name: Computer Controller
    description: null
    timeout: 300
    bundled: true
    available_tools: []
  tutorial:
    enabled: false
    type: builtin
    name: tutorial
    display_name: Tutorial
    description: null
    timeout: 300
    bundled: true
    available_tools: []
  developer:
    enabled: true
    type: builtin
    name: developer
    display_name: Developer
    description: null
    timeout: 300
    bundled: true
    available_tools: []
  memory:
    enabled: false
    type: builtin
    name: memory
    display_name: Memory
    description: null
    timeout: 300
    bundled: true
    available_tools: []
